program ::= command*

command ::= axiom-command
          | check-command
          | definition-command
          | notation-command

axiom-command ::= "Axiom" identifier+ ":" expr "."

check-command ::= "Check" expr "."

definition-command ::= definition-keyword identifier param-group* ":" expr ":=" expr "."

definition-keyword ::= "Definition" | "Procedure"

param-group ::= "(" identifier+ param-group-type? ")"
              | "{" identifier+ param-group-type? "}"

simple-param-group ::= identifier+ param-group-type?

param-group-type ::= ":" expr

notation-command ::= "Notation" identifier assoc prec expr "."

assoc ::= "left" | "right" | "none"

prec ::= nat

expr ::= ann | univ | pi | arrow | var | lit | app | partial-app | fun | hole | paren | binary

ann ::= simple-expr ":" expr

univ ::= "*" | "𝒰"

pi ::= pi-keyword param-group "," expr

pi-keyword ::= "∀" | "Π" | "forall"

arrow ::= expr "->" expr

var ::= identifier

lit ::= nat | string

app ::= expr expr+

partial-app ::= expr expr* "_"

fun ::= "fun" param-group+ "=>" expr
      | "fun" simple-param-group "=>" expr

hole ::= "??"

paren ::= "(" expr ")"

binary ::= expr op expr
